### ISSUE TITLE
[Tracking Issue] NZZC Cycle 2402

### ISSUE THREAD

**Issue by dirtyformal** [vatnz-dev/new-zealand-dataset#34]
### Preparation:
- [x] Prepare ANR data and commit to #ais-data-manager
- [x] Sort through AIP Bulletin and create tickets for each AD, noting the specific change.
- [x] Assess necessary changes to non-procedural data, such as Control Positions, frequencies, etc - raising project tickets where necessary.
- [x] Assess changes to Standard Route Data - raising project tickets where necessary.
- [x] Assess necessary changes to SOPs. Open a project ticket with a linked issue in the SOPs repository. Move to "Awaiting SOPs Change"

### Data Changes
- [x] Duplicate procedure changes in SFG, as per the relevant project ticket.
- [x] Implement any other changes required as a part of the AIP cycle.
- [x] Implement any backlog features.

### Testing
- [x] Test vatSys and EuroScope using the sweatbox environment.
- [x] Make sure all data files are valid, returning no XML errors.

### Release
- [x] Merge content into Master Release Repo
- [x] Publish Client Data Release.
- [x] If necessary, publish Standard Route Changes.
- [x] If necessary, publish SOP changes.
